---
- name: SSH Hardening Playbook
  hosts: fedora
  become: true
  vars:
    ssh_port: 2222

  tasks:
    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backup: yes

    - name: Enforce key-based login only
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        backup: yes

    - name: Change SSH port
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port'
        line: "Port {{ ssh_port }}"
        state: present
        backup: yes

    - name: Allow new SSH port in firewalld
      firewalld:
        port: "{{ ssh_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes

    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
